# Generated by Django 4.2.5 on 2023-09-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionmodel_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='category',
            new_name='address',
        ),
    ]
