# Generated by Django 4.2.5 on 2023-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_category_transactionmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transactionStatus',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
