# Generated by Django 4.2.5 on 2023-09-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_profilemodel_logo'),
        ('transactions', '0006_transactionmodel_addressstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_bank', to='company.companyinfomodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.companyinfomodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
