# Generated by Django 4.2.5 on 2023-09-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_profilemodel_logo'),
        ('transactions', '0008_transactionmodel_bankref_alter_transactionmodel_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.profilemodel'),
        ),
    ]
