# Generated by Django 4.2.5 on 2023-10-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_servicesmodel'),
        ('transactions', '0009_alter_transactionmodel_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docuemntType', models.CharField(blank=True, max_length=200, null=True)),
                ('documentQuantity', models.IntegerField(blank=True, null=True)),
                ('documentTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_inventory', to='inventory.inventorymodel')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_service', to='inventory.servicesmodel')),
            ],
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transactionDocuments',
            field=models.ManyToManyField(blank=True, default=None, related_name='documents', to='transactions.invoicedocumentsmodel'),
        ),
    ]
