# Generated by Django 4.2.5 on 2023-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_invoicedocumentsmodel_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
