# Generated by Django 4.2.5 on 2023-10-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transactionmodel_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='payments',
            field=models.ManyToManyField(blank=True, default=None, related_name='payment_history', to='transactions.paymenthistorymodel'),
        ),
    ]
