# Generated by Django 4.2.5 on 2023-10-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_paymenthistorymodel_transactionmodel_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='outstandingBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
