# Generated by Django 4.2.5 on 2023-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
