# Generated by Django 4.2.5 on 2023-09-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customermodel_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='fristName',
            new_name='firstName',
        ),
    ]
