# Generated by Django 4.2.5 on 2023-09-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_profilemodel_logo'),
        ('customers', '0003_rename_fristname_customermodel_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to='company.bankmodel'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
