# Generated by Django 4.2.5 on 2023-10-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_usermodel'),
        ('inventory', '0003_servicesmodel'),
        ('customers', '0004_customermodel_bank_customermodel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('beanUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to='client.usermodel')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_document', to='customers.customermodel')),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_document', to='inventory.inventorymodel')),
            ],
        ),
    ]
