# Generated by Django 4.2.5 on 2023-10-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_servicesmodel'),
        ('customers', '0006_rename_documentmodelview_documentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='services',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_document', to='inventory.servicesmodel'),
        ),
    ]
