# Generated by Django 4.2.5 on 2023-10-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_documentmodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
