# Generated by Django 4.2.5 on 2023-09-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('restocklevel', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('sellingprice', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='inventory.categorymodel')),
            ],
        ),
    ]
